# Generated by Django 6.0.6 on 2026-09-14 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('BOTH', 'Both')], default='CUSTOMER', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='e.g. +977-98XXXXXXXX. Kept as text: leading zeros and the country code matter.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('pan_number', models.CharField(blank=True, help_text="Permanent Account Number issued by Nepal's Inland Revenue Department.", max_length=20, verbose_name='PAN number')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'db_table': 'parties',
                'ordering': ['name'],
            },
        ),
    ]
