# Generated by Django 6.0.6 on 2026-09-08 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organization_memberships',
                'ordering': ['organization', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name if left blank. Used in URLs.', max_length=255, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, verbose_name='PAN number')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=7)),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=17)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
