# Generated by Django 6.0.6 on 2026-09-15 03:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_journalentry_journalentryline'),
        ('organizations', '0002_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(blank=True, max_length=30)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('narration', models.TextField(blank=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('party', models.ForeignKey(help_text="Must be a Vendor or Both -- enforced by the serializer's queryset, not here.", on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='parties.party')),
                ('payable_account', models.ForeignKey(blank=True, help_text='Accounts Payable control account credited when this bill is posted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills_as_payable', to='accounting.account')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('tax_receivable_account', models.ForeignKey(blank=True, help_text='Asset account (input tax/VAT receivable) debited for tax_amount. Required only if tax_amount > 0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills_as_tax_receivable', to='accounting.account')),
            ],
            options={
                'db_table': 'purchase_bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order', models.PositiveIntegerField(default=0)),
                ('expense_account', models.ForeignKey(blank=True, help_text='Expense account this line is debited to. Required by the time the bill is posted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasebill')),
            ],
            options={
                'db_table': 'purchase_bill_lines',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(fields=('organization', 'bill_number'), name='unique_bill_number_per_org'),
        ),
    ]
