# Generated by Django 6.0.6 on 2026-09-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Optional parent account, for grouping (e.g. 'Cash' under 'Current Assets').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text="Short account code, e.g. '1000'.", max_length=20),
        ),
    ]
