# Generated by Django 6.0.6 on 2026-09-15 02:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_journalentry_journalentryline'),
        ('organizations', '0002_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('narration', models.TextField(blank=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('party', models.ForeignKey(help_text="Must be a Customer or Both -- enforced by the serializer's queryset, not here.", on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='parties.party')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('receivable_account', models.ForeignKey(blank=True, help_text='Accounts Receivable control account debited when this invoice is posted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices_as_receivable', to='accounting.account')),
                ('tax_payable_account', models.ForeignKey(blank=True, help_text='Liability account credited for tax_amount when posted. Required only if tax_amount > 0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices_as_tax_payable', to='accounting.account')),
            ],
            options={
                'db_table': 'sales_invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order', models.PositiveIntegerField(default=0)),
                ('income_account', models.ForeignKey(blank=True, help_text="Income account this line's revenue is credited to. Required by the time the invoice is posted.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'sales_invoice_lines',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_invoice_number_per_org'),
        ),
    ]
